var s, classid, Sys = {},
ua = navigator.userAgent.toLowerCase();
(s = ua.match(/msie ([\d.]+)/)) ? Sys.ie = s[1] : (s = ua.match(/trident\/([\d.]+)/)) ? Sys.ie9 = s[1] : (s = ua.match(/firefox\/([\d.]+)/)) ? Sys.firefox = s[1] : (s = ua.match(/chrome\/([\d.]+)/)) ? Sys.chrome = s[1] : (s = ua.match(/opera.([\d.]+)/)) ? Sys.opera = s[1] : (s = ua.match(/version\/([\d.]+).*safari/)) ? Sys.safari = s[1] : 0,
classid = "A64E3073-2016-4baf-A89D-FFE1FAA10EC0",
Sys.ie || Sys.ie9 ? (document.write("<!-- 用来产生编辑状态的ActiveX控件的JS脚本-->   "), 
document.write("<!-- 因为微软的ActiveX新机制，需要一个外部引入的js-->   "), 
document.write('<object id="TANGER_OCX" classid="clsid:' + classid + '" '), 
document.write('codebase="ntko/OfficeControl.cab#version=5,0,2,7" width="100%" height="115px">   '), 
document.write('<param name="IsUseUTF8URL" value="-1">   '), 
document.write('<param name="IsUseUTF8Data" value="-1">   '), 
document.write('<param name="BorderStyle" value="1">   '),
document.write('<param name="BorderColor" value="14402205">   '), 
document.write('<param name="TitlebarColor" value="15658734">   '), 
document.write('<param name="TitlebarTextColor" value="0">   '),
document.write('<param name="MenubarColor" value="13158600">   '), 
document.write('<param name="MenuButtonColor" VALUE="16180947">   '),
document.write('<param name="MenuBarStyle" value="3">   '),
document.write('<param name="MenuButtonStyle" value="7">   '),
document.write('<param name="WebUserName" value="NTKO">   '), 
document.write('<param name="UILangCode" value="AUTO">   '), 
document.write('<param name="Serverpage" value="paaa.asp">   '),
document.write('<param name="Caption" value="NTKO OFFICE文档控件示例演示 http://www.ntko.com">   '), 
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。请点击<a href="media/office/NtkoOfficeControlSetup.msi">安装控件</a></SPAN>   '), 
document.write("</object>")) : Sys.chrome ? (document.write('<object id="TANGER_OCX" clsid="{' + classid + '}" '), 
document.write('type="application/ntko-plug" codebase="ntko/OfficeControl.cab#version=5,0,2,7" width="100%" height="115px"'), document.write('ForOnSaveToURL="OnComplete2" '), document.write('ForOnBeginOpenFromURL="OnComplete" '), 
document.write('ForOnDocumentOpened="DocumentOpened" '), document.write('ForOnpublishAshtmltourl="publishashtml" '), document.write('ForOnpublishAspdftourl="publishaspdf" '), document.write('ForOnSaveAsOtherFormatToUrl="saveasotherurl" '), 
document.write('ForOnDoWebGet="dowebget" '), 
document.write('ForOnDoWebExecute="webExecute" '),
document.write('ForOnDoWebExecute2="WebExecute" '), 
document.write('ForOnFileCommand="filecommand" '), 
document.write('ForOnCustomMenuCmd2="CustomMenuCmd" '), 
document.write('ForOnCustomToolBarCommand="CustomToolBarCom" '),
document.write('ForOnSignSelect="signselect" '), 
document.write('_IsUseUTF8URL="-1"   '), 
document.write('_IsUseUTF8Data="-1"   '), 
document.write('_BorderStyle="1"   '),
document.write('_BorderColor="14402205"   '),
document.write('_MenubarColor="14402205"   '),
document.write('_MenuButtonColor="16180947"   '), 
document.write('_MenuBarStyle="3"  '), 
document.write('_MenuButtonStyle="7"   '), 
document.write('_WebUserName="NTKO"   '), 
document.write('_CustomToolBar="-1"   '),
document.write('_Caption=" NTKO OFFICE文档控件示例演示" > '),
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。请点击<a href="media/office/NtkoOfficeControlSetup.msi">安装控件</a></SPAN>   '), 
document.write("</object>")) : Sys.firefox ? (document.write('<object id="TANGER_OCX" clsid="{' + classid + '}" '),
document.write('type="application/ntko-plug"  codebase="ntko/OfficeControl.cab#version=5,0,2,7" width="100%" height="115px" '), 
document.write('ForOnDocumentOpened="DocumentOpened" '), 
document.write('ForOnCustomToolBarCommand="CustomToolBarCom" '),
document.write('ForOnFileCommand="filecommand" '), 
document.write('ForAfterSaveAsPDFFile="aftersavepdffile" '),
document.write('ForOnpublishAshtmltourl="publishashtml" '), 
document.write('ForOnpublishAspdftourl="publishaspdf" '), 
document.write('ForOnSaveAsOtherFormatToUrl="saveasotherurl" '),
document.write('ForOnDoWebGet="dowebget" '), 
document.write('ForOnDoWebExecute="webExecute" '), 
document.write('ForOnDoWebExecute2="webExecute2" '),
document.write('ForOnCustomMenuCmd2="CustomMenuCmd" '),
document.write('ForOnSignSelect="signselect" '), 
document.write('_IsUseUTF8URL="-1"   '),
document.write('_IsUseUTF8Data="-1"   '), 
document.write('_BorderStyle="1"   '), 
document.write('_BorderColor="14402205"   '), 
document.write('_MenubarColor="14402205"   '),
document.write('_MenuButtonColor="16180947"   '), 
document.write('_MenuBarStyle="3"  '), 
document.write('_MenuButtonStyle="7"   '), 
document.write('_WebUserName="NTKO"   '), 
document.write('_CustomToolBar="-1"   '), 
document.write('_Caption="NTKO OFFICE文档控件示例演示"   >'),
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。请点击<a href="media/office/NtkoOfficeControlSetup.msi">安装控件</a></SPAN>   '), 
document.write("</object>   ")) : Sys.opera ? alert("sorry,ntko 暂时不支持opera!") : Sys.safari && alert("sorry,ntko 暂时不支持safari!");